openapi: 3.0.1
info:
  title: RootVaultAI Trust API
  description: Capsule minting, verification, and scoring engine
  version: "1.0.0"

servers:
  - url: https://rootvaultai-ppr1ewz9y-rootvaultai.vercel.app

paths:
  /api/mint:
    post:
      summary: Mint a Capsule
      operationId: mintCapsule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent_id:
                  type: string
                creator:
                  type: string
                metadata_uri:
                  type: string
                capsule_type:
                  type: string
              required: [agent_id, creator, metadata_uri, capsule_type]
      responses:
        "200":
          description: Capsule minted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  capsule_stored:
                    type: boolean
                  owner:
                    type: string
                  event:
                    type: string
        "400":
          description: Missing required fields
        "409":
          description: CapsuleAlreadyExists

  /api/trustscore/{agent_id}:
    get:
      summary: Get trustScore
      operationId: getTrustScore
      parameters:
        - in: path
          name: agent_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: trustScore result
          content:
            application/json:
              schema:
                type: object
                properties:
                  trustScore:
                    type: integer
                  reputation:
                    type: string
        "404":
          description: CapsuleNotFound

  /api/verify:
    post:
      summary: Verify a Capsule
      operationId: verifyCapsule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                capsule_id:
                  type: string
                verifying_agent:
                  type: string
              required: [capsule_id, verifying_agent]
      responses:
        "200":
          description: Verification complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
        "404":
          description: CapsuleNotFound
